# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AdminNote(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, creator_id: str=None, note: str=None, created_at: datetime=None, updated_at: datetime=None):  # noqa: E501
        """AdminNote - a model defined in Swagger

        :param user_id: The user_id of this AdminNote.  # noqa: E501
        :type user_id: str
        :param creator_id: The creator_id of this AdminNote.  # noqa: E501
        :type creator_id: str
        :param note: The note of this AdminNote.  # noqa: E501
        :type note: str
        :param created_at: The created_at of this AdminNote.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this AdminNote.  # noqa: E501
        :type updated_at: datetime
        """
        self.swagger_types = {
            'user_id': str,
            'creator_id': str,
            'note': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'creator_id': 'creator_id',
            'note': 'note',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._user_id = user_id
        self._creator_id = creator_id
        self._note = note
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'AdminNote':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The admin_note of this AdminNote.  # noqa: E501
        :rtype: AdminNote
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this AdminNote.


        :return: The user_id of this AdminNote.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this AdminNote.


        :param user_id: The user_id of this AdminNote.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def creator_id(self) -> str:
        """Gets the creator_id of this AdminNote.


        :return: The creator_id of this AdminNote.
        :rtype: str
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id: str):
        """Sets the creator_id of this AdminNote.


        :param creator_id: The creator_id of this AdminNote.
        :type creator_id: str
        """
        if creator_id is None:
            raise ValueError("Invalid value for `creator_id`, must not be `None`")  # noqa: E501

        self._creator_id = creator_id

    @property
    def note(self) -> str:
        """Gets the note of this AdminNote.


        :return: The note of this AdminNote.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note: str):
        """Sets the note of this AdminNote.


        :param note: The note of this AdminNote.
        :type note: str
        """
        if note is None:
            raise ValueError("Invalid value for `note`, must not be `None`")  # noqa: E501

        self._note = note

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this AdminNote.


        :return: The created_at of this AdminNote.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this AdminNote.


        :param created_at: The created_at of this AdminNote.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this AdminNote.


        :return: The updated_at of this AdminNote.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this AdminNote.


        :param updated_at: The updated_at of this AdminNote.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at
