# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class CountryUpdate(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None):
        """
        CountryUpdate - a model defined in Swagger

        :param name: The name of this CountryUpdate.
        :type name: str
        """
        self.swagger_types = {
            'name': str
        }

        self.attribute_map = {
            'name': 'name'
        }

        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'CountryUpdate':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The country_update of this CountryUpdate.
        :rtype: CountryUpdate
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this CountryUpdate.

        :return: The name of this CountryUpdate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this CountryUpdate.

        :param name: The name of this CountryUpdate.
        :type name: str
        """
        if name is not None and len(name) > 256:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `256`")

        self._name = name

