# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeleteUserUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, email: str=None, msisdn: str=None, reason: str=None, deleted_at: datetime=None, deleter_id: str=None):  # noqa: E501
        """DeleteUserUpdate - a model defined in Swagger

        :param username: The username of this DeleteUserUpdate.  # noqa: E501
        :type username: str
        :param email: The email of this DeleteUserUpdate.  # noqa: E501
        :type email: str
        :param msisdn: The msisdn of this DeleteUserUpdate.  # noqa: E501
        :type msisdn: str
        :param reason: The reason of this DeleteUserUpdate.  # noqa: E501
        :type reason: str
        :param deleted_at: The deleted_at of this DeleteUserUpdate.  # noqa: E501
        :type deleted_at: datetime
        :param deleter_id: The deleter_id of this DeleteUserUpdate.  # noqa: E501
        :type deleter_id: str
        """
        self.swagger_types = {
            'username': str,
            'email': str,
            'msisdn': str,
            'reason': str,
            'deleted_at': datetime,
            'deleter_id': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'msisdn': 'msisdn',
            'reason': 'reason',
            'deleted_at': 'deleted_at',
            'deleter_id': 'deleter_id'
        }

        self._username = username
        self._email = email
        self._msisdn = msisdn
        self._reason = reason
        self._deleted_at = deleted_at
        self._deleter_id = deleter_id

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteUserUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The delete_user_update of this DeleteUserUpdate.  # noqa: E501
        :rtype: DeleteUserUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this DeleteUserUpdate.


        :return: The username of this DeleteUserUpdate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this DeleteUserUpdate.


        :param username: The username of this DeleteUserUpdate.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this DeleteUserUpdate.


        :return: The email of this DeleteUserUpdate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this DeleteUserUpdate.


        :param email: The email of this DeleteUserUpdate.
        :type email: str
        """

        self._email = email

    @property
    def msisdn(self) -> str:
        """Gets the msisdn of this DeleteUserUpdate.


        :return: The msisdn of this DeleteUserUpdate.
        :rtype: str
        """
        return self._msisdn

    @msisdn.setter
    def msisdn(self, msisdn: str):
        """Sets the msisdn of this DeleteUserUpdate.


        :param msisdn: The msisdn of this DeleteUserUpdate.
        :type msisdn: str
        """

        self._msisdn = msisdn

    @property
    def reason(self) -> str:
        """Gets the reason of this DeleteUserUpdate.


        :return: The reason of this DeleteUserUpdate.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this DeleteUserUpdate.


        :param reason: The reason of this DeleteUserUpdate.
        :type reason: str
        """

        self._reason = reason

    @property
    def deleted_at(self) -> datetime:
        """Gets the deleted_at of this DeleteUserUpdate.


        :return: The deleted_at of this DeleteUserUpdate.
        :rtype: datetime
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at: datetime):
        """Sets the deleted_at of this DeleteUserUpdate.


        :param deleted_at: The deleted_at of this DeleteUserUpdate.
        :type deleted_at: datetime
        """

        self._deleted_at = deleted_at

    @property
    def deleter_id(self) -> str:
        """Gets the deleter_id of this DeleteUserUpdate.


        :return: The deleter_id of this DeleteUserUpdate.
        :rtype: str
        """
        return self._deleter_id

    @deleter_id.setter
    def deleter_id(self, deleter_id: str):
        """Sets the deleter_id of this DeleteUserUpdate.


        :param deleter_id: The deleter_id of this DeleteUserUpdate.
        :type deleter_id: str
        """
        if deleter_id is None:
            raise ValueError("Invalid value for `deleter_id`, must not be `None`")  # noqa: E501

        self._deleter_id = deleter_id
