# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeletedUserSiteUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, deletion_requested_at: datetime=None, deletion_requested_via: str=None, deletion_confirmed_at: datetime=None, deletion_confirmed_via: str=None):  # noqa: E501
        """DeletedUserSiteUpdate - a model defined in Swagger

        :param deletion_requested_at: The deletion_requested_at of this DeletedUserSiteUpdate.  # noqa: E501
        :type deletion_requested_at: datetime
        :param deletion_requested_via: The deletion_requested_via of this DeletedUserSiteUpdate.  # noqa: E501
        :type deletion_requested_via: str
        :param deletion_confirmed_at: The deletion_confirmed_at of this DeletedUserSiteUpdate.  # noqa: E501
        :type deletion_confirmed_at: datetime
        :param deletion_confirmed_via: The deletion_confirmed_via of this DeletedUserSiteUpdate.  # noqa: E501
        :type deletion_confirmed_via: str
        """
        self.swagger_types = {
            'deletion_requested_at': datetime,
            'deletion_requested_via': str,
            'deletion_confirmed_at': datetime,
            'deletion_confirmed_via': str
        }

        self.attribute_map = {
            'deletion_requested_at': 'deletion_requested_at',
            'deletion_requested_via': 'deletion_requested_via',
            'deletion_confirmed_at': 'deletion_confirmed_at',
            'deletion_confirmed_via': 'deletion_confirmed_via'
        }

        self._deletion_requested_at = deletion_requested_at
        self._deletion_requested_via = deletion_requested_via
        self._deletion_confirmed_at = deletion_confirmed_at
        self._deletion_confirmed_via = deletion_confirmed_via

    @classmethod
    def from_dict(cls, dikt) -> 'DeletedUserSiteUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deleted_user_site_update of this DeletedUserSiteUpdate.  # noqa: E501
        :rtype: DeletedUserSiteUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deletion_requested_at(self) -> datetime:
        """Gets the deletion_requested_at of this DeletedUserSiteUpdate.


        :return: The deletion_requested_at of this DeletedUserSiteUpdate.
        :rtype: datetime
        """
        return self._deletion_requested_at

    @deletion_requested_at.setter
    def deletion_requested_at(self, deletion_requested_at: datetime):
        """Sets the deletion_requested_at of this DeletedUserSiteUpdate.


        :param deletion_requested_at: The deletion_requested_at of this DeletedUserSiteUpdate.
        :type deletion_requested_at: datetime
        """

        self._deletion_requested_at = deletion_requested_at

    @property
    def deletion_requested_via(self) -> str:
        """Gets the deletion_requested_via of this DeletedUserSiteUpdate.


        :return: The deletion_requested_via of this DeletedUserSiteUpdate.
        :rtype: str
        """
        return self._deletion_requested_via

    @deletion_requested_via.setter
    def deletion_requested_via(self, deletion_requested_via: str):
        """Sets the deletion_requested_via of this DeletedUserSiteUpdate.


        :param deletion_requested_via: The deletion_requested_via of this DeletedUserSiteUpdate.
        :type deletion_requested_via: str
        """

        self._deletion_requested_via = deletion_requested_via

    @property
    def deletion_confirmed_at(self) -> datetime:
        """Gets the deletion_confirmed_at of this DeletedUserSiteUpdate.


        :return: The deletion_confirmed_at of this DeletedUserSiteUpdate.
        :rtype: datetime
        """
        return self._deletion_confirmed_at

    @deletion_confirmed_at.setter
    def deletion_confirmed_at(self, deletion_confirmed_at: datetime):
        """Sets the deletion_confirmed_at of this DeletedUserSiteUpdate.


        :param deletion_confirmed_at: The deletion_confirmed_at of this DeletedUserSiteUpdate.
        :type deletion_confirmed_at: datetime
        """

        self._deletion_confirmed_at = deletion_confirmed_at

    @property
    def deletion_confirmed_via(self) -> str:
        """Gets the deletion_confirmed_via of this DeletedUserSiteUpdate.


        :return: The deletion_confirmed_via of this DeletedUserSiteUpdate.
        :rtype: str
        """
        return self._deletion_confirmed_via

    @deletion_confirmed_via.setter
    def deletion_confirmed_via(self, deletion_confirmed_via: str):
        """Sets the deletion_confirmed_via of this DeletedUserSiteUpdate.


        :param deletion_confirmed_via: The deletion_confirmed_via of this DeletedUserSiteUpdate.
        :type deletion_confirmed_via: str
        """

        self._deletion_confirmed_via = deletion_confirmed_via
