# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SiteDataSchemaUpdate(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, schema: object=None):
        """
        SiteDataSchemaUpdate - a model defined in Swagger

        :param schema: The schema of this SiteDataSchemaUpdate.
        :type schema: object
        """
        self.swagger_types = {
            'schema': object
        }

        self.attribute_map = {
            'schema': 'schema'
        }

        self._schema = schema

    @classmethod
    def from_dict(cls, dikt) -> 'SiteDataSchemaUpdate':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The site_data_schema_update of this SiteDataSchemaUpdate.
        :rtype: SiteDataSchemaUpdate
        """
        return deserialize_model(dikt, cls)

    @property
    def schema(self) -> object:
        """
        Gets the schema of this SiteDataSchemaUpdate.

        :return: The schema of this SiteDataSchemaUpdate.
        :rtype: object
        """
        return self._schema

    @schema.setter
    def schema(self, schema: object):
        """
        Sets the schema of this SiteDataSchemaUpdate.

        :param schema: The schema of this SiteDataSchemaUpdate.
        :type schema: object
        """

        self._schema = schema

