# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserSiteDataUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, consented_at: date=None, blocked: bool=None, data: object=None):  # noqa: E501
        """UserSiteDataUpdate - a model defined in Swagger

        :param consented_at: The consented_at of this UserSiteDataUpdate.  # noqa: E501
        :type consented_at: date
        :param blocked: The blocked of this UserSiteDataUpdate.  # noqa: E501
        :type blocked: bool
        :param data: The data of this UserSiteDataUpdate.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'consented_at': date,
            'blocked': bool,
            'data': object
        }

        self.attribute_map = {
            'consented_at': 'consented_at',
            'blocked': 'blocked',
            'data': 'data'
        }

        self._consented_at = consented_at
        self._blocked = blocked
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'UserSiteDataUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_site_data_update of this UserSiteDataUpdate.  # noqa: E501
        :rtype: UserSiteDataUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def consented_at(self) -> date:
        """Gets the consented_at of this UserSiteDataUpdate.


        :return: The consented_at of this UserSiteDataUpdate.
        :rtype: date
        """
        return self._consented_at

    @consented_at.setter
    def consented_at(self, consented_at: date):
        """Sets the consented_at of this UserSiteDataUpdate.


        :param consented_at: The consented_at of this UserSiteDataUpdate.
        :type consented_at: date
        """

        self._consented_at = consented_at

    @property
    def blocked(self) -> bool:
        """Gets the blocked of this UserSiteDataUpdate.


        :return: The blocked of this UserSiteDataUpdate.
        :rtype: bool
        """
        return self._blocked

    @blocked.setter
    def blocked(self, blocked: bool):
        """Sets the blocked of this UserSiteDataUpdate.


        :param blocked: The blocked of this UserSiteDataUpdate.
        :type blocked: bool
        """

        self._blocked = blocked

    @property
    def data(self) -> object:
        """Gets the data of this UserSiteDataUpdate.


        :return: The data of this UserSiteDataUpdate.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this UserSiteDataUpdate.


        :param data: The data of this UserSiteDataUpdate.
        :type data: object
        """

        self._data = data
