# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UserSiteDataUpdate(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, data_processing_consent_provided: bool=None, data: object=None):
        """
        UserSiteDataUpdate - a model defined in Swagger

        :param data_processing_consent_provided: The data_processing_consent_provided of this UserSiteDataUpdate.
        :type data_processing_consent_provided: bool
        :param data: The data of this UserSiteDataUpdate.
        :type data: object
        """
        self.swagger_types = {
            'data_processing_consent_provided': bool,
            'data': object
        }

        self.attribute_map = {
            'data_processing_consent_provided': 'data_processing_consent_provided',
            'data': 'data'
        }

        self._data_processing_consent_provided = data_processing_consent_provided
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'UserSiteDataUpdate':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_site_data_update of this UserSiteDataUpdate.
        :rtype: UserSiteDataUpdate
        """
        return deserialize_model(dikt, cls)

    @property
    def data_processing_consent_provided(self) -> bool:
        """
        Gets the data_processing_consent_provided of this UserSiteDataUpdate.

        :return: The data_processing_consent_provided of this UserSiteDataUpdate.
        :rtype: bool
        """
        return self._data_processing_consent_provided

    @data_processing_consent_provided.setter
    def data_processing_consent_provided(self, data_processing_consent_provided: bool):
        """
        Sets the data_processing_consent_provided of this UserSiteDataUpdate.

        :param data_processing_consent_provided: The data_processing_consent_provided of this UserSiteDataUpdate.
        :type data_processing_consent_provided: bool
        """

        self._data_processing_consent_provided = data_processing_consent_provided

    @property
    def data(self) -> object:
        """
        Gets the data of this UserSiteDataUpdate.

        :return: The data of this UserSiteDataUpdate.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """
        Sets the data of this UserSiteDataUpdate.

        :param data: The data of this UserSiteDataUpdate.
        :type data: object
        """

        self._data = data

