"""empty message

Revision ID: 2bbdfe8e9112
Revises: ad34d26dd188
Create Date: 2018-08-08 09:54:08.237938

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '2bbdfe8e9112'
down_revision = 'ad34d26dd188'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    now = datetime.datetime.now().isoformat()
    empty_uuid = '00000000-0000-0000-0000-000000000000'
    # EDITED MIGRATION: Updates on existing fields where null are populated.
    sql = "UPDATE {table} SET {column} = {value} WHERE {column} IS NULL;"
    session.execute(sql.format(table="adminnote", column="created_at", value="'%s'" % now))
    session.execute(sql.format(table="adminnote", column="creator_id", value="'%s'" % empty_uuid))
    session.execute(sql.format(table="adminnote", column="note", value="'Empty Note'"))
    session.execute(sql.format(table="adminnote", column="updated_at", value="'%s'" % now))
    session.execute(sql.format(table="adminnote", column="user_id", value="'%s'" % empty_uuid))
    session.execute(sql.format(table="sitedataschema", column="created_at", value="'%s'" % now))
    session.execute(sql.format(table="sitedataschema", column="schema", value="jsonb_object('{}')"))
    session.execute(sql.format(table="sitedataschema", column="updated_at", value="'%s'" % now))
    session.execute(sql.format(table="usersitedata", column="created_at", value="'%s'" % now))
    session.execute(sql.format(table="usersitedata", column="data", value="jsonb_object('{}')"))
    session.execute(sql.format(table="usersitedata", column="updated_at", value="'%s'" % now))
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adminnote', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('adminnote', 'creator_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('adminnote', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('adminnote', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('adminnote', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('sitedataschema', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sitedataschema', 'schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('sitedataschema', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('usersitedata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('usersitedata', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('usersitedata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersitedata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('usersitedata', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('usersitedata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sitedataschema', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sitedataschema', 'schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sitedataschema', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('adminnote', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('adminnote', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('adminnote', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('adminnote', 'creator_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('adminnote', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
