"""empty message

Revision ID: ad34d26dd188
Revises: 4a3f1279bc80
Create Date: 2018-07-30 11:00:10.862609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad34d26dd188'
down_revision = '4a3f1279bc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleteduser',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('msisdn', sa.VARCHAR(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('deleter_id', postgresql.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletedusersite',
    sa.Column('deleted_user_id', postgresql.UUID(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_requested_via', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deletion_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_confirmed_via', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('deleted_user_id', 'site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deletedusersite')
    op.drop_table('deleteduser')
    # ### end Alembic commands ###
